### PR TITLE
Reduce use of Guava in file path handling.

### PR DESCRIPTION
**Pull request by mtbc**
This should not change behavior because it simply uses the standard library where we can easily avoid resorting to a third-party library. Server should work just as before.

### CODE REVIEW

**Comment by dominikl** [comment]
Looks good. Spun up a server, imported some images, worked fine. But as I'm not very familiar with the affected classes, maybe someone else should have a look too.

**Comment by rgozim** [comment]
Can't imagine changing from Guava to native libraries will have a much of a chance of breaking things. But yea, probably worth a look from someone with more knowledge of what the changes impact. At the very least, I'm sure omero-java integration tests will pick up any severe breakages.

**Comment by jburel** [comment]
I understand the logic behind changes but since you are fully removing the usage of guava, is that really necessary to modify few methods with possible side effect?

**Comment by rgozim** [comment]
@jburel there are also some changes using Java 8 Steam's, which I think are a bit cleaner than the previous code.

**Comment by mtbc** [comment]
See discussion at https://github.com/ome/omero-server/pull/34#issuecomment-488634155. Basically,

* I overhear enough grumbling about Guava and other third-party libraries that I try not to use them lightly.
* I've also heard comments that it's better to avoid third-party libraries when standard alternatives exist. Especially, I can see that:
  * When writing OMERO code people look at what code is already there so it is good if that existing code sets the desired example.
  * When reading OMERO code it is easier for developers if they see things done in what has become the normal way to do them.

Having said that, I could certainly have misapprehended the degree of others' aversion to using Guava where the SDK suffices.

**Comment by jburel** [comment]
I don't think you misunderstood but in the classes modified, there are still many guava functionalities still used so if people reviewing are unsure of the impact. is it worth the risks?

**Comment by mtbc** [comment]
> If there are no regression

seems to be harder to determine than I had expected.

**Comment by rgozim** [comment]
Guava contains a lot of utility classes that some could argue should have been part of the standard java library. I think, replacing the parts that have become standard Java over time is not such a bad idea.

C++ had a similar issue with smart pointers and the Boost libraries. Smart pointers eventually made their way into the standard, and the Boost ones were no longer the smart pointer of choice. This caused some issues with C++ libraries updating and their interfaces no longer being compatible with developers using the Boost smart pointers.

On the other hand, unlike Boost, Guava probably won't suffer the same fate as it follows the Collections API of Java very well.

I guess there is no straight forward answer :)

**Comment by mtbc** [comment]
Maybe best to just leave open a while then to give behavior changes time to be noticed.

**Comment by mtbc** [comment]
Also now pushed my last batch of reducing-Guava changes to https://github.com/ome/omero-blitz/pull/46 to give that time for any behavioral issues to be noticed.

**Pull request merged**
