### PR TITLE
M4

### PR DESCRIPTION
**Pull request by rgozim**

### CODE REVIEW

**Comment by jburel** [comment]
@rgozim you will have to roll back the change to SNAPSHOT since it has already been done in
another PR

**Comment by jburel** [comment]
With the last set of changes, it is now possible to build omero again
Next step before merging this PR is to fix the issue when reading snapshot from artifactory

**Comment by jburel** [comment]
After the last round of changes in the various repos, the omero server is now starting

**Comment by joshmoore** [comment]
Green from artifactory!

**Pull request merged**
