### PR TITLE
Remove the java gateway code

### PR DESCRIPTION
**Pull request by dominikl**
Removes the `omero.gateway.*` code, as this has been moved to https://github.com/ome/omero-java-gateway now.

### CODE REVIEW

**Comment by joshmoore** [comment]
This will require omero-gateway to be in added to omero-build as a submodule. Otherwise, devspace will fail tomorrow.

**Comment by jburel** [comment]
--exclude

**Comment by jburel** [comment]
--exclude

**Comment by jburel** [comment]
--exclude

**Comment by dominikl** [comment]
I'll just close it. Have to open a new PR later anyway, if we extract the gateway into it's own repository.

**Comment by jburel** [comment]
Re-open this PR so we can test in conjunction with https://github.com/ome/omero-model/pull/28

**Comment by jburel** [comment]
Tested with the new BF 6.1.0-m1 (which includes new guava version)
the "extraction" of omero-java-gateway from omero-blitz is now possible
We cannot include BF 6.1. yet since the omero pyramid reading is currently broken.
Excluding this PR for now

--exclude

**Pull request merged**
