### PR TITLE
Fixed compile errors

### PR DESCRIPTION
**Pull request by rgozim**

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks, @rgozim.

**Comment by joshmoore** [comment]
@rgozim : can you explain the differences between this and your previous develop?

```
@@ -99,11 +99,11 @@ dsl {
 slice {
     java {
         include = [
-                "src/generated/slice",
-                "src/main/slice"
+                file("src/generated/slice"),
+                file("src/main/slice")
         ]
-        files = fileTree(dir: "src/generated/slice", include: '**/*.ice') +
-                fileTree(dir: "src/main/slice", include: '**/*.ice')
+        files = fileTree(dir: file("src/generated/slice"), include: '**/*.ice') +
+                fileTree(dir: file("src/main/slice"), include: '**/*.ice')
         args = "--tie"
     }
 }
diff --git a/dsl.gradle b/dsl.gradle
deleted file mode 100644
index 56077cdb..00000000
--- a/dsl.gradle
+++ /dev/null
@@ -1,77 +0,0 @@
-// Runs the DSLTask OMERO plugin
-dsl {
-    def mappingsTree = project.fileTree(dir: project.buildDir, include: '**/*.ome.xml')
-
-    velocity {
-        resource_loader = 'file'
-        file_resource_loader_path = "${projectDir}/src/main/resources/templates"
-        file_resource_loader_cache = false
-    }
-
-    generate {
-        javaIceMap {
-            template = "java_ice_map.vm"
-            outFile = project.file("src/generated/java/omero/util/IceMap.java")
-            omeXmlFiles = mappingsTree
-        }
-
-        javaModelObjectFactoryRegistry {
-            template = "src/main/resources/templates/java_obj_reg.vm"
-            outFile = project.file("src/generated/java/omero/util//ModelObjectFactoryRegistry.java/")
-            omeXmlFiles = mappingsTree
-        }
-
-        cppModelObjectFactoryRegistry {
-            template = project.file("src/main/resources/templates/cpp_obj_reg.vm")
-            outFile = project.file("src/generated/cpp/omero/model/ObjectFactory.cpp")
-            omeXmlFiles = mappingsTree
-        }
-
-        pythonModelObjectFactoryRegistry {
-            template = new File("src/main/resources/templates/py_obj_reg.vm")
-            outFile = project.file("src/generated/python/omero/ObjectFactoryRegistrar.py")
-            omeXmlFiles = mappingsTree
-        }
-
-        combined {
-            template = new File("src/main/resources/templates/combined.vm")
-            outputPath = project.file("src/generated/combined")
-            omeXmlFiles = mappingsTree
-            formatOutput = { st ->
-                "${st.getShortname()}I.combined"
-            }
-        }
-    }
-}
-
-// This section takes the output of the combined.vm template and splits it into
-// the various sections. All of these files represent the Ice model and our
-// specializations of it
-def myCopySpec = project.copySpec {
-    from("src/generated/combined") {
-        include '**/*.combined'
-    }
-}
-
-static def filerLine(String line, String prefix) {
-    return line.matches("^\\[all](.*)|^\\[${prefix}](.*)") ?
-            line.replaceAll("^\\[all]|^\\[${prefix}]", "") :
-            null
-}
-
-// Handle headers
-task splitCppHeaders(type: Copy) {
-    into "src/generated/cpp/headers"
-    with myCopySpec
-    filter { filerLine(it, "hdr") }
-    rename '(.*?)I[.]combined', 'omero/model/$1I.h'
-}
-
-// Handles sources
-task splitCppSources(type: Copy) {
-    with myCopySpec
-    into "src/generated/cpp/sources"
-//    filter { line ->
-//        line.matches("\\[cpp]") ? line.replaceAll("\\[cpp]", "") : ""
-//    }
-}
diff --git a/mappings.gradle b/mappings.gradle
deleted file mode 100644
index 21959bad..00000000
--- a/mappings.gradle
+++ /dev/null
@@ -1,30 +0,0 @@
-configurations {
-    mappings
-}
-
-dependencies {
-    mappings 'org.openmicroscopy:omero-model:1.0-SNAPSHOT'
-}
-
-// CONSTANTS
-def EXTRACT_DIR = "${project.buildDir}/extracted/mappings"
-
-/* cleans the extracted omero-model folder */
-task cleanMappings(type: Delete) { delete EXTRACT_DIR }
-
-/* extracts and copies any .ome.xml file from omero-model */
-task importMappings(dependsOn: cleanMappings) {
-    doLast {
-        configurations.mappings.resolvedConfiguration.resolvedArtifacts.each { artifact ->
-            if (artifact.name != 'omero-model')
-                return
-            copy {
-                from zipTree(artifact.file).matching { include "**/*.ome.xml" }
-                into EXTRACT_DIR + '/' + artifact.name
-            }
-        }
-    }
-}
-
-/* Make sure importMappings runs before dsl */
-compileJava.dependsOn importMappings
\ No newline at end of file
```

The `file()` parts are definitely needed and I will push them to master now. What about the rest?

**Comment by rgozim** [comment]
dsl.gradle is never actually used for the final build process. It's function was for testing and iterating the design of the final blitz and dsl plugins. The file just got left behind.

**Comment by joshmoore** [comment]
K. Pushed a removal PR.

**Pull request merged**
