### PR TITLE
Have reset password use SQL to bypass 2019-SV3 restrictions.

### PR DESCRIPTION
**Pull request by mtbc**
Use https://github.com/ome/omero-model/pull/51 to fix the https://github.com/ome/openmicroscopy/pull/6230 failure of `testPasswordResetEmailGood`.

### CODE REVIEW

**Comment by mtbc** [comment]
Last commit to be omitted from merge, can push away once https://github.com/ome/omero-model/pull/51 is in. (Could I use `--depends-on` *within* a repo still to get that commit out to another PR?)

**Comment by mtbc** [comment]
This fixes the [integration test](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/lastCompletedBuild/testngreports/integration/ResetPasswordTest/testPasswordResetEmailGood/).

**Comment by joshmoore** [comment]
Along with:
 - https://github.com/ome/omero-model/pull/51
 - https://github.com/ome/openmicroscopy/pull/6230
the change here looks generally good. I still have a question about the order of operation. Do we want to merge sequentially, rolling back the travis fix. Or merge all the PRs and then use a quick jar release to tie them back together appropriately. Probably worth a quick chat.

**Comment by mtbc** [comment]
Once we tag omero-model I am happy to force-change that last commit accordingly to see if Travis stays green.

**Comment by joshmoore** [comment]
Thanks, @mtbc. @ome/release : that implies we would also try to _leave_ the `omero-model` pinning at the omero-server level to avoid the need for a rendering and romio PR.

**Comment by sbesson** [comment]
> @ome/release : that implies we would also try to leave the omero-model pinning at the omero-server level to avoid the need for a rendering and romio PR.

:+1: for using dependency management to reduce the number of unnecessary intermediate patch releases.

**Comment by joshmoore** [comment]
Things are looking green. :+1: I'm a _bit_ surprised by the need to have `api()` and `implementation()` statements, but barring that, LGTM.

**Comment by mtbc** [comment]
Is this mergeable or should I further adjust `build.gradle` somehow?

**Comment by joshmoore** [comment]
I don't the build.gradle, but I defer to you if there's a need for the duplication.

**Comment by mtbc** [comment]
There is, it won't build with one of them removed.

**Comment by joshmoore** [comment]
Testing on merge reaches https://github.com/ome/omero-blitz/blob/67fad3e9a2001de0322fb6e4a06065cc296f2a88/src/main/java/omero/cmd/admin/ResetPasswordRequestI.java#L174 i.e. passes the changes in this PR even though the send does not complete (due to local configuration).

**Comment by joshmoore** [comment]
Before merging, I pushed a commit matching my understanding of api/implementation. As @jburel points out, "API" should just say "compile and runtime" classpaths, while "implementation" should just be "runtime" class path. If this works out, I'd say good to go.

**Comment by mtbc** [comment]
Interesting, I wonder if I messed up my local build somehow when I tried. Travis seems happy now at least, yay.

**Comment by joshmoore** [comment]
:+1: Leaving the set of three PRs in your hand then.

**Comment by mtbc** [comment]
(You'll have to merge https://github.com/ome/openmicroscopy/pull/6230, I can't.)

**Comment by mtbc** [comment]
Thank you. :+1:

**Pull request merged**
