### PR TITLE
Updated build.gradle to use zeroc local plugin

### LINKED ISSUE #3: Publishing *.py, *.cpp, *.h files
The outputs of splitPython and splitCpp (if necessary, also splitHeaders) will need to be either captured during the omero-blitz build and published so they can be downloading by components/tools/OmeroPy or OmeroPy will need to make use of the new blitz plugin. (The latter is likely harder to start off with since gradle is not being used)

### PR DESCRIPTION
**Pull request by rgozim**
closes #3

### CODE REVIEW

**Comment by jburel** [comment]
Included in omero-build
```
A problem occurred configuring project ':omero-blitz'.
> Could not resolve all artifacts for configuration ':omero-blitz:classpath'.
  > Could not find gradle.plugin.com.zeroc.gradle.ice-builder:slice:1.5.0-SNAPSHOT. 
```

**Comment by joshmoore** [comment]
In my build, I see:

```
/home/omero/.m2/repository/com/zeroc/gradle/ice-builder/slice/1.5.0-SNAPSHOT/maven-metadata-local.xml
/home/omero/.m2/repository/com/zeroc/gradle/ice-builder/slice/1.5.0-SNAPSHOT/slice-1.5.0-SNAPSHOT.pom
/home/omero/.m2/repository/com/zeroc/gradle/ice-builder/slice/1.5.0-SNAPSHOT/slice-1.5.0-SNAPSHOT.jar
```

attempting to remove the "gradle.plugin" prefix.

**Comment by joshmoore** [comment]
The plugin seems to be found now, but I don't see any extra Python output. Does this need a new task with a new parameter (or similar)?

**Comment by jburel** [comment]
After unzipping the omero-blitz-python zip into ``dist/lib/python``, I have the following error
```
/src/dist$ bin/omero start
Traceback (most recent call last):
  File "bin/omero", line 102, in <module>
    import omero.cli
  File "/src/dist/lib/python/omero/__init__.py", line 8, in <module>
    import omero_API_ice
  File "/src/dist/lib/python/omero_API_ice.py", line 24, in <module>
    import omero_RTypes_ice
  File "/src/dist/lib/python/omero_RTypes_ice.py", line 24, in <module>
    import omero_model_IObject_ice
  File "/src/dist/lib/python/omero_model_IObject_ice.py", line 591, in <module>
    ('_id', (), _M_omero._t_RLong, False, 0),
AttributeError: 'module' object has no attribute '_t_RLong'
```

**Comment by jburel** [comment]
After unzipping the blitz-python zip under lib/fallback (so I did not override other files), and trying to start the server:
```
bin/omero start
Traceback (most recent call last):
  File "bin/omero", line 102, in <module>
    import omero.cli
  File "/src/dist/lib/python/omero/cli.py", line 52, in <module>
    from omero.util.concurrency import get_event
  File "/src/dist/lib/python/omero/omero/__init__.py", line 8, in <module>
    import omero_API_ice
  File "/src/dist/lib/fallback/omero_API_ice.py", line 24, in <module>
    import omero_RTypes_ice
  File "/src/dist/lib/fallback/omero_RTypes_ice.py", line 24, in <module>
    import omero_model_IObject_ice
  File "/src/dist/lib/fallback/omero_model_IObject_ice.py", line 591, in <module>
    ('_id', (), _M_omero._t_RLong, False, 0),
AttributeError: 'module' object has no attribute '_t_RLong'
```

**Comment by jburel** [comment]
Trying to start the server:
```
Traceback (most recent call last):
  File "bin/omero", line 102, in <module>
    import omero.cli
  File "/src/dist/lib/python/omero/cli.py", line 52, in <module>
    from omero.util.concurrency import get_event
  File "/src/dist/lib/python/omero/util/__init__.py", line 25, in <module>
    import omero.ObjectFactoryRegistrar as ofr
  File "/src/dist/lib/python/omero/ObjectFactoryRegistrar.py", line 10, in <module>
    class AcquisitionModeObjectFactory(Ice.ObjectFactory):
  File "/src/dist/lib/python/omero/ObjectFactoryRegistrar.py", line 12, in AcquisitionModeObjectFactory
    from omero_model_AcquisitionModeI import AcquisitionModeI
  File "/src/dist/lib/python/omero_model_AcquisitionModeI.py", line 1
    """
    ^
IndentationError: unexpected indent
```

**Comment by jburel** [comment]
all the generated classes are one space before any comment or code
This is not the case with the "old" build

**Comment by rgozim** [comment]
This line of code is responsible for outputting language files from the .combined files:

https://github.com/rgozim/omero-blitz-plugin/blob/e0dc0e6fa22f74a027c693a1ecef7ff8e7987e0c/src/main/groovy/org/openmicroscopy/blitz/tasks/SplitTask.groovy#L164

The regex may need changed.

**Comment by jburel** [comment]
The indent problem is now gone.
Error when attempting to start the server
```
File "/src/dist/lib/python/omero_model_IObject_ice.py", line 591, in <module>
    ('_id', (), _M_omero._t_RLong, False, 0),
AttributeError: 'module' object has no attribute '_t_RLong'
```

**Comment by joshmoore** [comment]
```
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:
```

:+1:

**Comment by jburel** [comment]
So the previous error is no longer there i.e. ``'module' object has no attribute '_t_RLong'``
now we have 
```
  File "/src/dist/lib/python/omero_model_AcquisitionModeI.py", line 30, in AcquisitionModeI
    details=_field_info_data(wrapper=omero.proxy_to_instance, nullable=True),
AttributeError: 'module' object has no attribute 'proxy_to_instance'
```

**Comment by joshmoore** [comment]
Corrected with https://github.com/openmicroscopy/openmicroscopy/pull/5934/commits/f5cd8d8ab583dffc325cadbf0fbc0ad28aed7bc2

**Comment by joshmoore** [comment]
Merging to get `omero-build` uptodate.

**Pull request merged**
